export const SHOW_ADVANCED = 'SHOW_ADVANCED'

export const RECENT_LOGIN_WALLET_ACCOUNT = 'RECENT_LOGIN_WALLET_ACCOUNT'

export const BLOCK_STATUS = 'BLOCK_STATUS'

export const LOADING_STATUS = 'LOADING_STATUS'

export const BLOCK_CONNETCTION_SIZE = 'BLOCK_CONNETCTION_SIZE'

export const WALLET_VERSION = 'WALLET_VERSION'

export const ACTIVE_HEADER_NAV = 'ACTIVE_HEADER_NAV'

